# Generated by Django 3.2.8 on 2021-11-20 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notice',
            new_name='notic',
        ),
    ]
